global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['bigdataproject-kafka-1:7071']

  - job_name: 'nifi'
    metrics_path: /metrics
    static_configs:
      - targets: ['bigdataproject-nifi-1:9091']
    honor_labels: true
    scrape_timeout: 10s
    scheme: http
    params:
      format: ["prometheus"]

  - job_name: 'spark'
    static_configs:
      - targets: ['bigdataproject-spark-1:4041']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['bigdataproject-minio-1:9000']
