lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames:
  - "org.apache.nifi.metrics:*"
  - "org.apache.nifi:*"
  - "java.lang:*"
rules:
  - pattern: "org.apache.nifi.metrics<type=(.+), name=(.+)><>Value"
    name: nifi_$1_$2
    type: GAUGE
  - pattern: ".*"